/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClockBackdrop: typeof import('./components/login/ClockBackdrop.vue')['default']
    ModulePlaceholder: typeof import('./components/admin/ModulePlaceholder.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NavIcon: typeof import('./components/admin/NavIcon.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPagination: typeof import('naive-ui')['NPagination']
    NSelect: typeof import('naive-ui')['NSelect']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    PageVeil: typeof import('./components/transition/PageVeil.vue')['default']
    PermissionManager: typeof import('./components/admin/PermissionManager.vue')['default']
    PermissionPicker: typeof import('./components/admin/PermissionPicker.vue')['default']
    RolePermissionPanel: typeof import('./components/admin/RolePermissionPanel.vue')['default']
    RoleTag: typeof import('./components/admin/RoleTag.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./components/admin/SideNav.vue')['default']
    StatusTag: typeof import('./components/admin/StatusTag.vue')['default']
    TabBar: typeof import('./components/admin/TabBar.vue')['default']
    UserDetailDrawer: typeof import('./components/admin/UserDetailDrawer.vue')['default']
    UserIdentity: typeof import('./components/admin/UserIdentity.vue')['default']
  }
}
